CREATE TABLE `user_t` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
	`type` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户类型. 0普通用户，1管理员',
	`email` VARCHAR(500) NOT NULL COMMENT '用户邮箱',
	`password` VARCHAR(500) NOT NULL COMMENT '用户密码',
	`name` VARCHAR(500) NOT NULL COMMENT '用户昵称',
	`sex` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '用户性别. 0男性1女性',
	`ctime` DATETIME NOT NULL COMMENT '创建时间',
	`utime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后修改时间',
	PRIMARY KEY (`id`)
)
COMMENT='用户表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `sku_t` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
	`name` VARCHAR(500) NOT NULL COMMENT '产品名称',
	`pic_url` VARCHAR(1000) NOT NULL COMMENT '产品图',
	`description` VARCHAR(1000) NOT NULL COMMENT '产品介绍',
	`price` FLOAT UNSIGNED NOT NULL COMMENT '产品价格',
	`num` INT(10) UNSIGNED NOT NULL COMMENT '库存',
	`status` INT(10) UNSIGNED NOT NULL COMMENT '状态,1上架，0下架',
	`ctime` DATETIME NOT NULL COMMENT '创建时间',
	`utime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后修改时间',
	PRIMARY KEY (`id`)
)
COMMENT='产品表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;


CREATE TABLE `order_t` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '订单ID，自增主键',
	`user_id` BIGINT(20) NOT NULL COMMENT '下单用户',
	`sku_id` BIGINT(20) NOT NULL COMMENT 'skuId',
	`position` VARCHAR(1000) NOT NULL COMMENT '配送地址',
	`ctime` DATETIME NOT NULL COMMENT '下单时间',
	`utime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后修改时间',
	PRIMARY KEY (`id`)
)
COMMENT='订单表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;


CREATE TABLE `collect_t` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
	`user_id` BIGINT(20) NOT NULL COMMENT '用户ID',
	`sku_id` BIGINT(20) NOT NULL COMMENT 'skuId',
	`ctime` DATETIME NOT NULL COMMENT '创建时间',
	`utime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后修改时间',
	PRIMARY KEY (`id`)
)
COMMENT='收藏表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
